import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers as ChakraUiProvider } from "@/provider-configs/chakraui/ChakraProvider";
import Navbar from "@/components/navbar/Navbar";
import { Box } from "@chakra-ui/react";
import { PriceProvider } from "@/context/PriceContext";
import Footer from "@/components/sections/Footer";
import RQProviders from "@/provider-configs/reactquery/RQProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sumatif",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <RQProviders>
          <ChakraUiProvider>
            <PriceProvider>
              <Box>
                <Navbar />
              </Box>
              {children}
              <Footer />
            </PriceProvider>
          </ChakraUiProvider>
        </RQProviders>
      </body>
    </html>
  );
}
