import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers as ChakraUiProvider } from "@/provider-configs/chakraui/ChakraProvider";
import Navbar from "@/components/navbar/Navbar";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sumatif",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ChakraUiProvider>
          <Box
            px={{ base: 4, md: 10, lg: 16 }}
            pt={5}
          >
            <Navbar />
          </Box>
          {children}
        </ChakraUiProvider>
      </body>
    </html>
  );
}
